services:
  aircraft-ground-ops:
    build:
      context: ./
      dockerfile: Dockerfile 
    image: aircraft-ground-ops:latest
    ports:
      - "8080:8080"
    restart: always
    container_name: aircraft-ground-ops